version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: CapstoneCont
    volumes:
      - .:/Capstone
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=capstone2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

volumes:
  db_volume: